server:
  port: 8081
  servlet:
    context-path: /hs-kleinanzeigen

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:4406/KLEINANZEIGEN?useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: start01

# use the following properties to execute DDL on startup
  sql.init.mode: never
  jpa:
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl

  liquibase:
    change-log: classpath:/liquibase/db.changeLog.xml

  cache:
    type: redis
    redis:
      time-to-live: 600000

management:
  endpoints:
    web:
      exposure:
        include: "*"
  
